name: BUILD SDK
on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.18.1'
      - name: Installing dependencies
        run: yarn install
      - name: Building project
        run: yarn build
      - name: Running tests
        run: yarn test

