name: BUILD SDK
on: [pull_request]

jobs:
  deploy:
    name: Deploy to NPM
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.18.1'
      - name: Installing dependencies
        run: yarn install
      - name: Building project
        run: yarn build
      - name: Running tests
        run: yarn test
      - name: Conditional publish to NPM
        run: node .github/willPublish.js
