name: PUBLISH
on:
  push:
    branches:
      # TODO: Change to master, eventually...
      - auto_deploy

jobs:
  deploy:
    name: Deploy to NPM
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.18.1'
      - name: Installing dependencies
        run: yarn install
      - name: Building project
        run: yarn build
      - name: Running tests
        run: yarn test
      - name: Evaluate package versions
        id: will_publish
        run: echo ::set-output name=RESPONSE::$(node ./.github/willPublish.js)
      - name: Conditional publish to NPM
        if: ${{ endsWith(steps.will_publish.outputs.RESPONSE, '!!_DO_PUBLISH_!!') }}
        run: echo I WILL PUBLISH
      - name: No deploy publish to NPM sample
        if: ${{ endsWith(steps.will_publish.outputs.RESPONSE, '!!_DO_NOT_PUBLISH_!!') }}
        run: echo WONT PUBLISH :-(
